config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do

  resources :notifications, only: [:index,:update]
  resources :posts
  resources :usuarios, as: :users,only: [:show,:update]
  resources :friendships, only: [:create,:update,:index]

  devise_for :users, controllers:{
  	omniauth_callbacks: "users/omniauth_callbacks"
  }

  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"

  

  authenticated :user do
  	root 'main#home'
  end

  unauthenticated :user do
  	root 'main#unregistered'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'

end


#ESTE CODIGO VA ARRIBA PARA LAS PRUEBAS CON rspec con la carpeta spec
#devise_for :users, controllers:{
 #   omniauth_callbacks: "users/omniauth_callbacks"
  #}

app/views/partials/_nav.html.erb
<header class="mdl-layout__header mdl-layout__header--scroll">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title">  <%= link_to "Red Social" ,root_path, class:"white-text right-space", style: "text-decoration:none;"%>  </span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation -->
      <nav class="mdl-navigation relative">
         <!-- links navegacion -->
         <% if user_signed_in? %>
         <div id="notifications"></div>

         <div class="right-space">

          <%= link_to "/notifications" , class:"circle red white-text", id:"notification",remote: true,data: {type: "script"} do%> 
            <%=current_user.unviewed_notifications_count  %> 

          <% end %> 

         </div>


          <%= link_to current_user.username , current_user, class:"white-text right-space"%> 


         <%= link_to "Mis amigos" , friendships_path, class:"white-text right-space"%> 

            <%= link_to "Cerrar sesiòn" , destroy_user_session_path, method: :delete ,class:"white-text"%> 
         <% end %> 

      </nav>
    </div>
  </header>

  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">Red Social</span>
    <nav class="mdl-navigation">
       <!-- links navegacion lado izquierdo -->
    </nav>
  </div>